name: Update Flake Inputs
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
  repository_dispatch:
jobs:
  update-flake-inputs:
    runs-on: nix
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.HYPERBOT_GITEA_TOKEN }}
      - name: Update flake inputs
        uses: Mic92/update-flake-inputs-gitea@main
        with:
          gitea-token: ${{ secrets.HYPERBOT_GITEA_TOKEN }}
          github-token: ${{ secrets.HYPERBOT_GITHUB_TOKEN }}
          auto-merge: true
          base-branch: next
          git-author-name: hyperbot
          git-author-email: hyperbot@enzim.ee
          git-committer-name: hyperbot
          git-committer-email: hyperbot@enzim.ee
