#!/usr/bin/env bash

if [[ -e $(git rev-parse --show-toplevel)/.git-blame-ignore-revs ]]; then
    echo ".git-blame-ignore-revs detected, setting blame.ignoreRevsFile"
    git config --local blame.ignoreRevsFile .git-blame-ignore-revs
else
    echo "Unsetting blame.ignoreRevsFile"
    git config --local --unset blame.ignoreRevsFile
fi
